security:
  basic:
    enabled: true
  user:
    name: ralap
    password: hjx969190

server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://ralap:hjx969190@localhost:${server.port}/eureka/