
spring:
  application:
    name: movie-consumer
  datasource:
    url : jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username : root
    password : 123
    driverClassName : org.mariadb.jdbc.Driver
    max-active : 20
    max-idle : 8
    min-idle : 8
    initial-size : 10
    hikari:
          max-lifetime: 1765000
          maximum-pool-size: 10
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://ralap:hjx969190@localhost:8761/eureka/
  instance:
    prefer-ip-address: true